[[commands]]
  id = "steam_open"
  type = "ahk"
  exe_path = "ahk/Open steam.exe"
  sounds.ru = ["game_mode"]
  sounds.en = ["ok1"]
  phrases.ru = [
      "включи игровой режим",
      "перейди в игровой режим",
      "я хочу поиграть",
      "включи стим",
      "запусти стим",
      "открой стим",
  ]

  [[commands]]
  id = "steam_close"
  type = "ahk"
  exe_path = "ahk/Close steam.exe"
  sounds.ru = ["ok1", "ok2", "ok3", "ok4"]
  sounds.en = ["ok1", "ok2", "ok3"]
  phrases.ru = [
      "рабочий режим",
      "вернись в рабочий режим",
      "отключи игровой режим",
      "выйди из игрового режима",
      "выход с игрового режима",
      "рабочее пространство",
      "выключи игровой режим",
      "выключи стим",
      "отключи стим",
      "выйди из стима",
      "закрой стим",
  ]
  